spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/.well-known/jwks.json
  cloud:
    gateway:
      routes:
        - id: sso-auth
          uri: http://localhost:8090
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /auth/$\{segment}
        - id: sso-jwks
          uri: http://localhost:8090
          predicates:
            - Path=/.well-known/jwks.json
        - id: inventory-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/orders/**
        - id: payment-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/payments/**
        - id: shipment-via-order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/shipments/**
