server:
  port: ${PORT:8093}

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://sso-service-lvow.onrender.com/.well-known/jwks.json
  cloud:
    gateway:
      routes:
        - id: sso-auth
          uri: https://sso-service-lvow.onrender.com
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth/(?<segment>.*), /auth/$\{segment}
        - id: sso-jwks
          uri: https://sso-service-lvow.onrender.com
          predicates:
            - Path=/.well-known/jwks.json
        - id: inventory-service
          uri: https://ordernest-inventory-service.onrender.com
          predicates:
            - Path=/api/products/**
        - id: order-service
          uri: https://ordernest-order-service.onrender.com
          predicates:
            - Path=/api/orders/**
        - id: payment-service
          uri: https://ordernest-payment-service.onrender.com
          predicates:
            - Path=/api/payments/**
        - id: shipment-via-order-service
          uri: https://ordernest-order-service.onrender.com
          predicates:
            - Path=/api/shipments/**
